package main

// ConnectorOutput represents the output file generated by the connector
type ConnectorOutput struct {
	ConnectorID        string             `json:"connectorId,omitempty"`
	ConnectorVersion   string             `json:"connectorVersion,omitempty"`
	IntegrationVersion string             `json:"integrationVersion,omitempty"`
	Description        string             `json:"description,omitempty"`
	Content            []KubernetesObject `json:"content,omitempty"`
}

// KubernetesObject describes an object that is read from the kubernetes api
type KubernetesObject struct {
	Type string                 `json:"type,omitempty"`
	ID   string                 `json:"id,omitempty"`
	Data map[string]interface{} `json:"data,omitempty"`
}

// KubernetesNodeInfo holds meta information about a kubernetes cluster
type KubernetesNodeInfo struct {
	DataCenter        string
	AvailabilityZones []string
	NumberNodes       int
	NodeTypes         []string
}
