package mapper

// KubernetesObject describes an object that is read from the kubernetes api
type KubernetesObject struct {
	Type string                 `json:"type,omitempty"`
	ID   string                 `json:"id,omitempty"`
	Data map[string]interface{} `json:"data,omitempty"`
}

// LDIF (LEAN Data Interchange Format) represents the output file generated by the connector
type LDIF struct {
	ConnectorID        string             `json:"connectorId,omitempty"`
	ConnectorVersion   string             `json:"connectorVersion,omitempty"`
	IntegrationVersion string             `json:"integrationVersion,omitempty"`
	Description        string             `json:"description,omitempty"`
	Content            []KubernetesObject `json:"content,omitempty"`
}
